### ISSUE TITLE
Change example; mention idempotency

### ISSUE THREAD

**Issue by bartelink** [volak/TodoMVC-DDD-CQRS-EventSourcing#4]
> (One example would be trying to invoice a sales order twice)

I'd suggest changing this to editing a sales order that has already been invoiced. In general, as I'm sure you are aware, command processing is best designed in such a way that the processing of a command generally be idempotent in nature - so if it is the same request (e.g. bearing the same originating requestor's requestId guid), the second request should also return a HTTP Accepted response rather than something like Conflict or a 400

**Comment by volak** [comment]
Thanks for the suggestion!  Thats what I meant when I wrote it but it could also be interpreted as "many of the same command" as you point out so I changed the wording.

(sorry for the lateness github notifications are terrible and Im currently updating this project to 2020)
