### ISSUE TITLE
What would a UnitTest for ToDo look like?

### ISSUE THREAD

**Issue by hellfirehd** [volak/TodoMVC-DDD-CQRS-EventSourcing#5]
I really like Aggregates.NET compared to all the other DDD/ES/CQRS libraries and examples I've seen.  It's by far the cleanest and most thorough implementation.

I've been working through this example app and It's a decent primer, just missing a sample of unit tests for ToDo.

I was going to take a crack and setting some up myself, but several of the Interfaces and Classes I would use (based on Aggregates.NET.UnitTests Test class) are internal and thus I'm a bit stumped.

I'd be happy to submit a pull request to add the UnitTests for ToDo but I'm stalled.

**Comment by volak** [comment]
I am sorry! I know people complain about this all the time but github's notification system for issues is really really terrible.
No emails, no highlighted boxes, no indication that any of my projects received a new issue..

Your question is a good one I take it you've looked at the unit test examples in Aggregates.Net examples folder? https://github.com/volak/Aggregates.NET/blob/master/samples/1.%20HelloWorld/1.%20Tests/World.cs
as well as the ones in the sample Store project? 
https://github.com/volak/eShopOnContainersDDD/blob/master/src/Contexts/Basket/Domain/Tests/Basket/CreateDestroy.cs


I am currently in the process of updating this project to all the new packages and versions / usages.  I'll be sure to include some tests to cover the todo domain

**Comment by volak** [comment]
Sorry for the wait but updating the project took longer than expected since I moved off of ServiceStack in favor of Asp Net Web Api.

The tests project has been added to test application and domain logic!

https://github.com/volak/TodoMVC-DDD-CQRS-EventSourcing/blob/master/src/Test/DomainHandler.cs
